### PR TITLE
Defer scrollToPosition() and fix IndexOutOfBounds crash

### LINKED ISSUE #31: Problem with saving the state of recyclerView
Hey guys

I have a problemwith saving the state of Recycler View using Greedo Layout Manager. I get this exception when calling:

`recyclerView.scrollToPosition(index);`

in onResume()

`03-06 12:35:55.287 20863-20863/com.artland E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.artland, PID: 20863
                                                             java.lang.RuntimeException: Invalid content width. Did you forget to set it?
                                                                 at com.fivehundredpx.greedolayout.GreedoLayoutSizeCalculator.computeChildSizesUpToPosition(GreedoLayoutSizeCalculator.java:101)
                                                                 at com.fivehundredpx.greedolayout.GreedoLayoutSizeCalculator.getRowForChildPosition(GreedoLayoutSizeCalculator.java:79)
                                                                 at com.fivehundredpx.greedolayout.GreedoLayoutManager.rowForChildPosition(GreedoLayoutManager.java:278)
                                                                 at com.fivehundredpx.greedolayout.GreedoLayoutManager.scrollToPosition(GreedoLayoutManager.java:306)
`

Any idea on how to fix it? Weird thing is, that both setContentWidth() and setMaxRowHeight() are public void methods, but I can only use setMaxRowHeight() when configuring the GreedoLayoutManager. setContentWidth() is not even visible as a useable method. 

Would highly appreciate any help! @mck182

### PR DESCRIPTION
**Pull request by mck182**
This PR fixes two crashes related to `scrollToPosition()` calls.

### Defer scrollToPosition() after layouting is fully finished
If scrollToPosition() is called before the postLayout pass, the
LayoutManager has no knowledge about its own sizes yet and therefore the
scroll operation cannot be completed and the safety checks in
GreedoLayoutSizeCalculator will crash on that.

So this defers the scrollToPosition() call to after the layout is
finished. Should fix #31 

### Fix index-out-of-bounds crash
With certain positions (usually those on the start of the row) this can
crash with java.lang.IndexOutOfBoundsException. The problem is that
we're checking the position with mRowForChildPosition.size() and then
computing all the child sizes *up to* the position (ie. not including
the position). This can lead to crashes as can be seen in
#20

### CODE REVIEW

File: greedo-layout/src/main/java/com/fivehundredpx/greedolayout/GreedoLayoutSizeCalculator.java [hunk 1]
```diff
@@ -76,7 +80,7 @@ public int getFirstChildPositionForRow(int row) {
 
     public int getRowForChildPosition(int position) {
         if (position >= mRowForChildPosition.size()) {
-            computeChildSizesUpToPosition(position);
+            computeChildSizesUpToPosition(position + 1);
```
Comment (JVillella) [inline greedo-layout/src/main/java/com/fivehundredpx/greedolayout/GreedoLayoutSizeCalculator.java]: Alternatively we could update the check in `computeChildSizesUpToPosition` so we get the desired behaviour anywhere that method is called.

Comment (mck182) [inline greedo-layout/src/main/java/com/fivehundredpx/greedolayout/GreedoLayoutSizeCalculator.java]: Yep, that'd be nicer, I moved it.
